#!/usr/bin/env node
//
// Regenerate docs/DEPENDENCIES.md — the dependency + licence inventory
// required by CDC §3.2 ("liste des dépendances et licences utilisées").
//
//   node tools/licenses.cjs
//
// Deliberately depends on nothing. A licence report is exactly the kind
// of thing that must still run in five years, on a checkout nobody has
// touched, without a tool that has since been deprecated or renamed —
// so it reads node_modules directly rather than pulling in a scanner.
//
// It reports the declared licence of every direct dependency. Transitive
// packages are counted, not listed: the tree runs to over a thousand
// packages and a list that long is read by nobody. `npm ls --all` gives
// the full tree when an audit genuinely needs it.

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

function readInstalled(name) {
  try {
    const p = path.join(root, 'node_modules', ...name.split('/'), 'package.json');
    const meta = JSON.parse(fs.readFileSync(p, 'utf8'));
    let license = meta.license || meta.licenses || 'UNKNOWN';
    if (Array.isArray(license)) {
      license = license.map((l) => l.type || l).join(' OR ');
    } else if (typeof license === 'object') {
      license = license.type || 'UNKNOWN';
    }
    return {
      version: meta.version || '?',
      license,
    };
  } catch {
    // Not installed in this checkout — say so rather than guess.
    return { version: '?', license: 'NOT INSTALLED' };
  }
}

function table(deps) {
  const rows = Object.keys(deps)
    .sort()
    .map((name) => {
      const info = readInstalled(name);
      return `| \`${name}\` | ${info.version} | ${deps[name]} | ${info.license} |`;
    });
  return ['| Package | Installed | Range | Licence |', '| --- | --- | --- | --- |', ...rows].join('\n');
}

function licenceTally(...groups) {
  const tally = {};
  for (const deps of groups) {
    for (const name of Object.keys(deps)) {
      const { license } = readInstalled(name);
      tally[license] = (tally[license] || 0) + 1;
    }
  }
  return Object.entries(tally)
    .sort((a, b) => b[1] - a[1])
    .map(([lic, n]) => `| ${lic} | ${n} |`);
}

function countTransitive() {
  const dir = path.join(root, 'node_modules');
  if (!fs.existsSync(dir)) return null;
  let n = 0;
  for (const entry of fs.readdirSync(dir)) {
    if (entry.startsWith('.')) continue;
    if (entry.startsWith('@')) {
      const scoped = path.join(dir, entry);
      if (fs.statSync(scoped).isDirectory()) n += fs.readdirSync(scoped).length;
      continue;
    }
    n += 1;
  }
  return n;
}

const prod = pkg.dependencies || {};
const dev = pkg.devDependencies || {};
const transitive = countTransitive();

const out = `<!-- Generated by \`node tools/licenses.cjs\`. Do not edit by hand. -->

# Dependencies and licences

The inventory required by CDC §3.2 ("liste des dépendances et licences
utilisées"). Regenerate after adding or upgrading anything:

\`\`\`bash
node tools/licenses.cjs
\`\`\`

**The app itself:** \`${pkg.name}\` ${pkg.version} — licensed
**${pkg.license}**, like the upstream \`c2c_ui\` it is forked from.

Generated ${new Date().toISOString().slice(0, 10)}.

## What matters

- **${Object.keys(prod).length} direct production dependencies**, each listed below with its licence.
- **${Object.keys(dev).length} development dependencies** (build, lint, tests) — none of them ship to the browser.
${
  transitive
    ? `- **~${transitive} packages installed in total** once transitive ones are counted. \`npm ls --all\` prints the full tree; it is not copied here because a list that long is read by nobody.\n`
    : ''
}
## Licence breakdown (direct dependencies)

| Licence | Count |
| --- | --- |
${licenceTally(prod, dev).join('\n')}

No strong copyleft (GPL/AGPL) among the **direct** dependencies. This
table does not cover transitive ones: before redistributing, run a
scanner over the full tree. The app's own copyleft comes from its own
code, inherited from \`c2c_ui\`, not from what it consumes.

## Production dependencies

${table(prod)}

## Development dependencies

${table(dev)}

## Notes

- A licence shown as \`UNKNOWN\` means the package does not declare one
  in its \`package.json\`: read it from the project repository before
  redistributing.
- \`NOT INSTALLED\` means the package was missing from the \`node_modules\`
  of the machine that generated this file — run \`npm install\` and
  regenerate.
`;
const target = path.join(root, 'docs', 'DEPENDENCIES.md');
fs.writeFileSync(target, out);

// Hand the file to prettier, which owns markdown formatting in this repo
// (`npm run lint`). Without this, every regeneration would leave the tree
// lint-dirty and the next contributor would 'fix' a generated file by
// hand. Best-effort: a missing prettier is not a reason to fail.
try {
  require('child_process').execFileSync(
    process.execPath,
    [require.resolve('prettier/bin-prettier.js'), '--write', target],
    {
      stdio: 'ignore',
    }
  );
} catch {
  console.warn('prettier unavailable — run `npm run lint` before committing.');
}

console.log(`docs/DEPENDENCIES.md written — ${Object.keys(prod).length} prod, ${Object.keys(dev).length} dev.`);
